version: "3.8"

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: brawlworld
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - brawl

  nginx:
    image: nginx:latest
    container_name: nginx-brawlworld
    restart: always
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - brawl

  db:
    image: mysql:latest
    container_name: brawl-mysql
    restart: unless-stopped
    ports:
      - "3309:3306"
    networks:
      - brawl
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: brawl
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  brawl:
    driver: bridge
    name: brawl

volumes:
  mysql_data:
